### ISSUE TITLE
chrome not reachable

### ISSUE THREAD

**Issue by gprasad84** [sitespeedio/sitespeed.io-docker#5] opened 2016-01-05 23:23 UTC
I am encountering issues when running sitespeed on chrome using docker container : 

`docker run --privileged --rm -v /tmp:/sitespeed.io sitespeedio/sitespeed.io:3.11.1  sitespeed.io -u http://www.sitespeed.io -b chrome -n 1`

[UnknownError: chrome not reachable (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.10.0-327.3.1.el7.x86_64 x86_64)] code: 100, state: 'unknown error', message: 'chrome not reachable\n (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.10.0-327.3.1.el7.x86_64 x86_64)', name: 'UnknownError', stack: 'UnknownError: chrome not reachable\n (Driver info: chromedriver=2.20.353124 

However it works fine when I download the tool locally and run with option `-b chrome`

Below is the console ouput of the error : 

`[root@localhost vagrant]# docker run --privileged --rm -v /tmp:/sitespeed.io sitespeedio/sitespeed.io:3.11.1  sitespeed.io -u http://www.sitespeed.io -b chrome -n 1
Tue Jan  5 23:05:24 UTC 2016
ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b)
Google Chrome 46.0.2490.71 
Mozilla Firefox 41.0.2
Starting Xvfb ...
Starting Selenium server ... access it at http://127.0.0.1:4444/wd/hub
info: OS: 'linux 3.10.0-327.3.1.el7.x86_64', Node.js: 'v4.2.1', sitespeed.io: '3.11.1', PhantomJS: '1.9.8', java: '1.7.0_79', browsertime: '0.12.0'
info: Will crawl from start point http://www.sitespeed.io with crawl depth 1
info: Will analyze 13 pages
info: Running YSlow for http://www.sitespeed.io [phantomjs]
info: Running YSlow for https://www.sitespeed.io/documentation/rules-and-best-practices/ [phantomjs]
info: Running YSlow for https://www.sitespeed.io/documentation/performance-budget/ [phantomjs]
info: Running YSlow for https://www.sitespeed.io/documentation/graphs/ [phantomjs]
info: Running YSlow for https://www.sitespeed.io/documentation/ [phantomjs]
info: Running YSlow for https://www.sitespeed.io/aboutus/ [phantomjs]
info: Running YSlow for https://www.sitespeed.io/example/ [phantomjs]
info: Running YSlow for https://www.sitespeed.io [phantomjs]
info: Running YSlow for https://www.sitespeed.io/logo/ [phantomjs]
info: Running YSlow for https://www.sitespeed.io/faq/ [phantomjs]
info: Running YSlow for https://www.sitespeed.io/documentation/installation/ [phantomjs]
info: Running YSlow for https://www.sitespeed.io/documentation/performance-dashboard/ [phantomjs]
info: Running YSlow for https://www.sitespeed.io/documentation/browsers/ [phantomjs]
Starting proxy on port 2001, will wait at most 15000 ms
info: Queueing browsertime for http://www.sitespeed.io chrome
info: Queueing browsertime for https://www.sitespeed.io/documentation/rules-and-best-practices/ chrome
info: Queueing browsertime for https://www.sitespeed.io/documentation/performance-budget/ chrome
info: Queueing browsertime for https://www.sitespeed.io/documentation/graphs/ chrome
info: Queueing browsertime for https://www.sitespeed.io/documentation/ chrome
info: Queueing browsertime for https://www.sitespeed.io/aboutus/ chrome
info: Queueing browsertime for https://www.sitespeed.io/example/ chrome
info: Queueing browsertime for https://www.sitespeed.io chrome
info: Queueing browsertime for https://www.sitespeed.io/logo/ chrome
info: Queueing browsertime for https://www.sitespeed.io/faq/ chrome
info: Queueing browsertime for https://www.sitespeed.io/documentation/installation/ chrome
info: Queueing browsertime for https://www.sitespeed.io/documentation/performance-dashboard/ chrome
info: Queueing browsertime for https://www.sitespeed.io/documentation/browsers/ chrome
info: Running browsertime for chrome http://www.sitespeed.io
Fetching http://www.sitespeed.io (1 of 1)
{ [UnknownError: chrome not reachable
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.10.0-327.3.1.el7.x86_64 x86_64)]
  code: 100,
  state: 'unknown error',
  message: 'chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.10.0-327.3.1.el7.x86_64 x86_64)',
  name: 'UnknownError',
  stack: 'UnknownError: chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.10.0-327.3.1.el7.x86_64 x86_64)\n    at new bot.Error (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)\n    at Object.bot.response.checkResponse (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:160:24\n    at promise.ControlFlow.runInFrame_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)\n    at goog.defineClass.notify (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)\n    at promise.Promise.notify_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)\n    at Array.forEach (native)\n    at promise.Promise.notifyAll_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)\n    at goog.async.run.processWorkQueue (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)\n    at process._tickCallback (node.js:366:9)\nFrom: Task: WebDriver.createSession()\n    at Function.webdriver.WebDriver.acquireSession_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)\n    at Function.webdriver.WebDriver.createSession (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)\n    at new Driver (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/chrome.js:810:36)\n    at Builder.build (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/builder.js:454:14)\n    at Object.module.exports.getDriver (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsers/chrome.js:41:49)\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:107:64\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/async/lib/async.js:721:13\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/async/lib/async.js:52:16\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/async/lib/async.js:269:32\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/async/lib/async.js:44:16' }
info: Running browsertime for chrome https://www.sitespeed.io/documentation/rules-and-best-practices/
error: Error running browsertime: { [UnknownError: chrome not reachable
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.10.0-327.3.1.el7.x86_64 x86_64)]
  code: 100,
  state: 'unknown error',
  message: 'chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.10.0-327.3.1.el7.x86_64 x86_64)',
  name: 'UnknownError',
  stack: 'UnknownError: chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.10.0-327.3.1.el7.x86_64 x86_64)\n    at new bot.Error (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)\n    at Object.bot.response.checkResponse (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:160:24\n    at promise.ControlFlow.runInFrame_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)\n    at goog.defineClass.notify (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)\n    at promise.Promise.notify_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)\n    at Array.forEach (native)\n    at promise.Promise.notifyAll_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)\n    at goog.async.run.processWorkQueue (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)\n    at process._tickCallback (node.js:366:9)\nFrom: Task: WebDriver.createSession()\n    at Function.webdriver.WebDriver.acquireSession_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)\n    at Function.webdriver.WebDriver.createSession (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)\n    at new Driver (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/chrome.js:810:36)\n    at Builder.build (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/builder.js:454:14)\n    at Object.module.exports.getDriver (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsers/chrome.js:41:49)\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:107:64\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/async/lib/async.js:721:13\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/async/lib/async.js:52:16\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/async/lib/async.js:269:32\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/async/lib/async.js:44:16' }
error: Error running browsertime: [Error: Error from server: 455]
info: Running browsertime for chrome https://www.sitespeed.io/documentation/performance-budget/
error: Error running browsertime: [Error: Error from server: 455]
info: Running browsertime for chrome https://www.sitespeed.io/documentation/graphs/
error: Error running browsertime: [Error: Error from server: 455]
error: Error running browsertime: [Error: Error from server: 455]
info: Running browsertime for chrome https://www.sitespeed.io/documentation/
info: Running browsertime for chrome https://www.sitespeed.io/aboutus/
error: Error running browsertime: [Error: Error from server: 455]
info: Running browsertime for chrome https://www.sitespeed.io/example/
error: Error running browsertime: [Error: Error from server: 455]
info: Running browsertime for chrome https://www.sitespeed.io
error: Error running browsertime: [Error: Error from server: 455]
info: Running browsertime for chrome https://www.sitespeed.io/logo/
error: Error running browsertime: [Error: Error from server: 455]
error: Error running browsertime: [Error: Error from server: 455]
info: Running browsertime for chrome https://www.sitespeed.io/faq/
info: Running browsertime for chrome https://www.sitespeed.io/documentation/installation/
error: Error running browsertime: [Error: Error from server: 455]
info: Running browsertime for chrome https://www.sitespeed.io/documentation/performance-dashboard/
error: Error running browsertime: [Error: Error from server: 455]
info: Running browsertime for chrome https://www.sitespeed.io/documentation/browsers/
error: Error running browsertime: [Error: Error from server: 455]
Stopping proxy
error: Could not generate HAR for https://www.sitespeed.io/documentation/rules-and-best-practices/ { [Error: ENOENT: no such file or directory, open '/sitespeed.io/sitespeed-result/www.sitespeed.io/2016-01-05-23-05-26/data/har/chrome/s-www_sitespeed_io-documentation-rules-and-best-practices-.har']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/sitespeed.io/sitespeed-result/www.sitespeed.io/2016-01-05-23-05-26/data/har/chrome/s-www_sitespeed_io-documentation-rules-and-best-practices-.har' }
error: Could not generate HAR for https://www.sitespeed.io/documentation/ { [Error: ENOENT: no such file or directory, open '/sitespeed.io/sitespeed-result/www.sitespeed.io/2016-01-05-23-05-26/data/har/chrome/s-www_sitespeed_io-documentation-.har']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/sitespeed.io/sitespeed-result/www.sitespeed.io/2016-01-05-23-05-26/data/har/chrome/s-www_sitespeed_io-documentation-.har' }
error: Could not generate HAR for https://www.sitespeed.io/documentation/performance-budget/ { [Error: ENOENT: no such file or directory, open '/sitespeed.io/sitespeed-result/www.sitespeed.io/2016-01-05-23-05-26/data/har/chrome/s-www_sitespeed_io-documentation-performance-budget-.har']
`

**Comment by soulgalore** [comment] 2016-01-06 20:37
Hi @gprasad84 
I tested it now and it  ... (exciting yes?) worked for me. hmm strange. I've seen the error before but it then usually happens when we have open a lot of different chrome instances or if it is a missmatch in versions between chrome & the chromedriver.

@tobli do you see what's wrong?

Best
Peter

**Comment by gprasad84** [comment] 2016-01-07 02:00
Hi @soulgalore 
Thanks for looking into it.
Update : It seems to work for me when I run the docker command in a Mac OSX environment (via docker toolbox). But surprisingly fails with the above error on a Linux environment.

Here is the docker version I am using on the linux environment :

docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

**Comment by abhagupta** [comment] 2016-01-14 02:20
I am getting the exact same issue and it happens with only few versions of Linux.  When drilled down into the processes and watching how `chrome` is opening in the container, I see chrome is opening as `chrome-sandbox` vs `chrome` in my MAC which opens chrome successfully. So far I have not found a solution, but https://github.com/jfrazelle/dockerfiles/issues/65  could give some clues.  @soulgalore  I am trying to find a way to run chrome as `--no-sandbox` option. I am not super familiar with creating Docker images yet, but is there a simple way we can send in `--no-sandbox` option without changing the Dockerfile and recreating the image?   I tried sending as a part of  `docker run` but it didn't seem to accept it.

**Comment by soulgalore** [comment] 2016-01-14 06:14
Hi @abhagupta thanks for looking into it! You can set the <code>--no-sandbox</code> to Browsertime (that opens the browser) using the <code>noSandbox</code>. It isn't super clear how to do it right now, but at least you can try it out if it works. 

You need to create a JSON file:

<pre>{
 "noSandbox": true
}
</pre> 

and pass it to your sitespeed run with <code>--btConfig filename</code>

And running in Docker you need to have that file reachable inside your container mounting a volume.

If it works we can do a patch so it automatically is set or something (or at least add some docs).
Ping @tobli !

Best
Peter

**Comment by abhagupta** [comment] 2016-01-14 19:04
Hi @soulgalore . Your approach worked. After passing the `--noSandbox` option, chrome opens up and runs the test successfully.  Thanks so much!!!

**Comment by abhagupta** [comment] 2016-01-18 19:22
@soulgalore , @tobli I found that Firefox suffers with a similar issue . The process of Firefox runs with `/usr/lib/firefox/firefox -foreground` option inside docker container, which is not able to open the firefox in arch linux. I confirmed this by manually fetching the url with the `-foreground` vs without `-foreground` from inside a running container.     Could you provide me with FF counterpart of  `--noSandbox` in Chrome? Tried `--noForeground`, but that didn't work.    Thanks

**Comment by soulgalore** [comment] 2016-01-20 09:54
Hi @abhagupta how should I do to reproduce it? What should I run on etc?

Best
Peter

**Comment by abhagupta** [comment] 2016-01-20 21:18
@soulgalore , Below is my Linux distribution information for the host VM

```
-bash-4.2$ cat /etc/*-release
CentOS Linux release 7.0.1406 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CentOS Linux release 7.0.1406 (Core) 
CentOS Linux release 7.0.1406 (Core) 
IMAGE_RELEASE="RC6"
```

Note: I apologize, I thought my linux distribution is Arch linux, but its not.

```
-bash-4.2$ cat /proc/version 
Linux version 3.10.0-123.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) #1 SMP Mon Jun 30 12:09:22 UTC 2014
```

```
-bash-4.2$ uname --all
Linux wml-docker-sitespeed-2628574-1-94369941 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

```
-bash-4.2$ uname -o
GNU/Linux
```

```
-bash-4.2$ sudo docker --version
Docker version 1.6.0, build 8aae715/1.6.0
```

Information of sitespeed and browsertime when test is executed:

```
info: OS: 'linux 3.10.0-123.el7.x86_64', Node.js: 'v4.2.2', sitespeed.io: '3.11.1', PhantomJS: '1.9.8', java: '1.7.0_85', browsertime: '0.12.0'

```

command:

```
sudo docker run --privileged --rm -v /data/sitespeed.io:/sitespeed.io registry.docker.walmart.com/abhagupta/sitespeed-firefox sitespeed.io -u http://cwe-board00.sv.walmartlabs.com:8000/test.html -b firefox -n 11 --connection cable -r /tmp/ --graphiteHost 10.227.65.156 --seleniumServer http://127.0.0.1:4444/wd/hub
```

Note: `registry.docker.walmart.com/abhagupta/sitespeed-firefox`  is an exact copy of the `sitespeedio/sitespeed.io-firefox` , just it is inside our internal registry because the host VMs cannot access external network.

**Comment by soulgalore** [comment] 2016-01-22 19:59
Hi @abhagupta ,
thanks, I'll check if I can spin up an instance on Digital Ocean and test, will ping you if I need help :)

Best
Peter

**Comment by Eimji** [comment] 2016-02-18 06:25
Hello,
I have the same issue when running the sitespeed docker with chrome. 
I create a file named chrome-fix.json containing the proposed fix for chrome not reachable:
{
 "noSandbox": true
}
I put this file in my current directory: ~/data/dev/sitespeed, then I run this command:
docker run --privileged --rm -v /home/patrick/data/dev/sitespeed:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://www.yahoo.fr -b chrome --connection native ----btConfig chrome-fix.json
But I still get the error. Please tell me if I'm doing something wrong with the file nosandbox. 

I'm using Debian Jessie with the kernel 4.3.3 from Debian backports repository.

Thanks in advance for your help.

**Comment by Eimji** [comment] 2016-02-18 13:30
Please forget my previous message.

Your proposed fix for chrome not reachable does work great. I made a mistake myself.
Thanks for your work.

**Comment by rmarx** [comment] 2016-06-15 07:58
I had the same problems with both Chrome and Firefox.
Chrome was fixed with the "noSandbox" option.

For firefox, it eventually turned out to be that I was using an outdated version of selenium (2.47) which doesn't support Firefox 43+ (see also this selenium issue: https://github.com/seleniumhq/selenium/issues/1395). So for me, it had nothing to do with the -foreground flag.

Since the latest NPM package for browsertime is still 0.12.2, which contains selenium 2.47, I had to manually update to selenium 2.53 using:
`npm install selenium-webdriver@2.53 --save` in `/sitespeed/node_modules/browsertime`

This seems to work fine with both Chrome, Firefox and SlimerJS from sitespeed. 
My setup is in a custom docker container based on Ubuntu 16.04, running on a Debian 8 host.

**Comment by bizmate** [comment] 2020-04-01 05:37
can this be closed? it looks like an old resolved issue

**Comment by soulgalore** [comment] 2020-04-01 13:30
yes!

**Closed as completed by soulgalore** 2020-04-01 13:30 UTC

**Comment by vaibhavi789** [comment] 2022-09-06 14:30
I have similar issue .. chrome not reachable 
I have ubuntu docker container
<img width="775" alt="Screenshot 2022-09-06 at 15 29 12" src="https://user-images.githubusercontent.com/58173901/188661646-c63f7ee1-630c-41bc-a5b9-e8f1fb17eaf9.png">

**Comment by soulgalore** [comment] 2022-09-08 07:35
Hi @vaibhavi789 can you please try with the latest container  **sitespeedio/sitespeed.io:25.11.0** - looking at the versions you are using a quite old one. If you still have issues, please create a new issue and add more info (like base os etc) so I can have a look. Thanks!
